name: Integration Tests

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  vitest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.4
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          # - ubuntu-latest
          - windows-2019
          - windows-2022
          - windows-2025
          # - windows-latest

    name: "Run tests: ${{ matrix.os }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, pcntl, fileinfo, pdo, sqlite, pdo_sqlite, pdo_mysql, pdo_pgsql intl, ftp, zip
          coverage: pcov

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run build
        run: bun run build

      - name: Run tests
        run: bun run test

  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          # - ubuntu-latest
#          - windows-2019
#          - windows-2022
#          - windows-2025
          # - windows-latest
        php:
          - 8.4
          # - 8.5
        postgres:
          - 13
          - 14
          - 15
          - 16
          - 17
#        database:
#          - sqlite
#          - mysql
#          - postgres
        stability:
          - prefer-stable
          - prefer-lowest

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

    name: "Run tests: PHP ${{ matrix.php }} - ${{ matrix.postgres }} - ${{ matrix.stability }} - ${{ matrix.os }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, pcntl, fileinfo, pdo, sqlite, pdo_sqlite, pdo_mysql, intl, ftp, zip, redis
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

#      - name: "Setup MySQL"
#        if: ${{ matrix.database == 'mysql' }}
#        uses: ankane/setup-mysql@v1
#        with:
#          mysql-version: 8.0
#          database: "app"

      - name: Set database config
        run: php -r "copy('tests/Fixtures/Config/database.postgres.php', 'tests/Fixtures/Config/database.config.php');"

      - name: Tempest about
        run: php ./tempest about -v

      - name: List discovered locations
        run: php ./tempest discovery:status

      - name: Execute tests
        run: php -d"error_reporting = E_ALL & ~E_DEPRECATED" -dmemory_limit=1G vendor/bin/phpunit
